name: Run Tests
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  unit-tests:
    runs-on: ubuntu-latest

    steps:
      # Setup
      - name: Checkout Repository
        uses: actions/checkout@v6
        with:
          submodules: true

      - name: Install CppUTest
        run: |
          sudo apt-get update
          sudo apt-get install -y cpputest

      - name: Run CMake
        run: |
          cmake -B build -DCMAKE_BUILD_TYPE=Debug -DBUILD_TESTING=ON
      
      # Build and Run Tests with Reporting and Coverage
      - name: Run Common Unit Tests
        working-directory: ./build
        run: |
          make test_common_report

      - name: Run ERV Unit Tests
        working-directory: ./build
        run: |
          make test_erv_report

      - name: Run Ichor Unit Tests
        working-directory: ./build
        run: |
          make test_ichor_report
      
      # Post Processing
      - name: Upload Test Results
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: build/test_reports/**/cpputest_*.xml
        if: ${{ !cancelled() }}
      
      # TODO: Decide between lcov, gcov, gcovr, codecov, coveralls, and SonarQube for code coverage reporting