---
# This is in a separate file because it is recommended to have
# different permissions than the test runner for public repos
# name: Test Report
# In test-report.yml, add this after name:
run-name: Test Report triggered by ${{ github.event.workflow_run.workflow_id }}

on:
  workflow_run:
    workflows: ["Run Tests"]
    types:
      - completed
permissions:
  contents: read
  actions: read
  checks: write
jobs:
  test-report:
    runs-on: ubuntu-latest
    steps:
      - name: Test Report Summary
        uses: dorny/test-reporter@v2
        with:
          artifact: test-results
          name: CppUTest Report
          reporter: java-junit
          path: |
            build/reports/**/cpputest_*.xml